import './globals.css'
import DarkThemeProvider from '@/providers/DarkThemeProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DarkThemeProvider>
          {children}
        </DarkThemeProvider>
      </body>
    </html>
  )
}
